---
- hosts: newsbuddy-workers
  remote_user: bitboy

  tasks:

  - name: create users
    user: name=archiveteam
    become: yes
    become_method: su

  - name: install prereq packages
    become: yes
    become_method: su
    apt: pkg={{item}} state=installed update_cache=yes
    with_items:
     - git
     - build-essential
     - python3-dev
     - python3-pip
     - youtube-dl
     - sudo
     - screen
     - xinetd
     - htop
     - nload
     - nmon
     - tree
     - vim

  - name: create directory structure
    become: yes
    become_method: su
    file: path={{item}} state=directory mode=0755 owner=archiveteam group=archiveteam
    with_items:
     - /home/archiveteam/newsbuddy
     - /home/archiveteam/newsbuddy/new_lists
     - /home/archiveteam/newsbuddy/old_lists
     - /home/archiveteam/newsbuddy/ready

  - name: install rsync target pointer
    become: yes
    become_method: su
    copy: src=templates/rsync_target dest=/home/archiveteam/newsbuddy

  - name: install rsyncd defaults config
    become: yes
    become_method: su
    copy: src=templates/rsync dest=/etc/default/rsync
    
  - name: install xinetd rsync service config
    become: yes
    become_method: su
    copy: src=templates/xinetdrsyncservice dest=/etc/xinetd.d/rsync

  - name: install rsyncd config
    become: yes
    become_method: su
    copy: src=templates/rsyncd.conf dest=/etc/rsyncd.conf
    
  - name: restart xinetd
    become: yes
    become_method: su
    command: /etc/init.d/xinetd restart

  - name: install grab-site
    become: yes
    become_method: su
    pip: name='git+https://github.com/ludios/grab-site.git#egg=grab-site' executable=pip3

  - name: deploy worker script
    git: repo=https://github.com/ArchiveTeam/NewsGrabber.git dest=/home/archiveteam/NewsGrabber
    become: yes
    become_user: archiveteam

  - name: symlink worker file
    file: src=/home/archiveteam/NewsGrabber/worker.py dest=/home/archiveteam/newsbuddy/worker.py state=link
    become: yes
    become_user: archiveteam
    
  - name: symlink grab-site to ~/.local/bin
    file: src=/usr/local/bin/grab-site dest=/home/archiveteam/.local/bin/grab-site state=link
    become: yes
    become_method: su

  - name: start worker process
    command: screen -dm python worker.py
    args:
      chdir: /home/archiveteam/newsbuddy/
    become: yes
    become_user: archiveteam

#  - name: announce rsync target to irc
#    script: scripts/irc.sh
